run:
  build-tags:
    - unit
    - integration
  skip-files:
    - driver/inmemory/matcher_gen.go

linters:
  enable:
    - govet
    - errcheck
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - revive
    - ineffassign
    - staticcheck
    - unconvert
    - vet
    - vetshadow

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    # Ignore the streamEvents.Close errcheck warning since we do not want to introduce a logger for repositories just yet
    - path: aggregate/repository.go
      text: "Error return value of \\`streamEvents.Close\\` is not checked"
      linters:
        - errcheck

    - linters:
        - revive
      text: "package-comments:"
