version: "2"
run:
  build-tags:
    - unit
    - integration
linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - revive
    - unconvert
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
        path: aggregate/repository.go
        text: Error return value of \`streamEvents.Close\` is not checked
      - linters:
          - revive
        text: 'package-comments:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
