// Code generated by a developer because lint is complaining about the package name DO NOT EDIT.
// TODO: remove the above line
//
// Package goengine_dev is a set of packages that provide many tools for event sourcing.
package goengine_dev

// In order to avoid lots having to manually write similar code use `go generate` to generate the code
//go:generate go run internal/tools/eventstore_inmemory_gen.go

// In order to make sure that we have the same mocks we can regenerate them using `go generate`
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=EventStore -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=EventStream -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir eventstore/ -name=PayloadFactory -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir eventstore/ -name=PayloadConverter -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir eventstore/ -name=PayloadResolver -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir eventstore/ -name=PersistenceStrategy -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir eventstore/ -name=Query -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir eventstore/sql/ -name=MessageFactory -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=Message -outpkg mocks -output ./mocks -case underscore
