// Code generated by a developer because lint is complaining about the package name DO NOT EDIT.
// TODO: remove the above line
//
// Package goengine_dev is a set of packages that provide many tools for event sourcing.
package goengine

// In order to make sure that we have the same mocks we can regenerate them using `go generate`
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=EventStore -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=EventStream -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=MessagePayloadFactory -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=MessagePayloadConverter -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=MessagePayloadResolver -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir strategy/ -name=PersistenceStrategy -outpkg strategy -output ./mocks/strategy -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=Query -outpkg mocks -output ./mocks -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir driver/sql/ -name=MessageFactory -outpkg sql -output ./mocks/driver/sql -case underscore
//go:generate go run vendor/github.com/vektra/mockery/cmd/mockery/mockery.go -dir ./ -name=Message -outpkg mocks -output ./mocks -case underscore
