// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hellofresh/goengine/v2/aggregate (interfaces: Root)

// Package aggregate is a generated GoMock package.
package aggregate

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aggregate "github.com/hellofresh/goengine/v2/aggregate"
)

// AnotherRoot is a mock of Root interface.
type AnotherRoot struct {
	aggregate.BaseRoot
	ctrl     *gomock.Controller
	recorder *AnotherRootMockRecorder
}

// AnotherRootMockRecorder is the mock recorder for AnotherRoot.
type AnotherRootMockRecorder struct {
	mock *AnotherRoot
}

// NewAnotherRoot creates a new mock instance.
func NewAnotherRoot(ctrl *gomock.Controller) *AnotherRoot {
	mock := &AnotherRoot{ctrl: ctrl}
	mock.recorder = &AnotherRootMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AnotherRoot) EXPECT() *AnotherRootMockRecorder {
	return m.recorder
}

// AggregateID mocks base method.
func (m *AnotherRoot) AggregateID() aggregate.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(aggregate.ID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID.
func (mr *AnotherRootMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*AnotherRoot)(nil).AggregateID))
}

// Apply mocks base method.
func (m *AnotherRoot) Apply(arg0 *aggregate.Changed) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Apply", arg0)
}

// Apply indicates an expected call of Apply.
func (mr *AnotherRootMockRecorder) Apply(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*AnotherRoot)(nil).Apply), arg0)
}
