// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hellofresh/goengine/aggregate (interfaces: Root)

// Package aggregate is a generated GoMock package.
package aggregate

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aggregate "github.com/hellofresh/goengine/aggregate"
)

// Root is a mock of Root interface
type Root struct {
	aggregate.BaseRoot
	ctrl     *gomock.Controller
	recorder *RootMockRecorder
}

// RootMockRecorder is the mock recorder for Root
type RootMockRecorder struct {
	mock *Root
}

// NewRoot creates a new mock instance
func NewRoot(ctrl *gomock.Controller) *Root {
	mock := &Root{ctrl: ctrl}
	mock.recorder = &RootMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Root) EXPECT() *RootMockRecorder {
	return m.recorder
}

// AggregateID mocks base method
func (m *Root) AggregateID() aggregate.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(aggregate.ID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID
func (mr *RootMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*Root)(nil).AggregateID))
}

// Apply mocks base method
func (m *Root) Apply(arg0 *aggregate.Changed) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Apply", arg0)
}

// Apply indicates an expected call of Apply
func (mr *RootMockRecorder) Apply(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*Root)(nil).Apply), arg0)
}
