// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import goengine_dev "github.com/hellofresh/goengine-dev"
import metadata "github.com/hellofresh/goengine/metadata"
import mock "github.com/stretchr/testify/mock"

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

// AppendTo provides a mock function with given fields: ctx, streamName, streamEvents
func (_m *EventStore) AppendTo(ctx context.Context, streamName goengine_dev.StreamName, streamEvents []goengine_dev.Message) error {
	ret := _m.Called(ctx, streamName, streamEvents)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, goengine_dev.StreamName, []goengine_dev.Message) error); ok {
		r0 = rf(ctx, streamName, streamEvents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, streamName
func (_m *EventStore) Create(ctx context.Context, streamName goengine_dev.StreamName) error {
	ret := _m.Called(ctx, streamName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, goengine_dev.StreamName) error); ok {
		r0 = rf(ctx, streamName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasStream provides a mock function with given fields: ctx, streamName
func (_m *EventStore) HasStream(ctx context.Context, streamName goengine_dev.StreamName) bool {
	ret := _m.Called(ctx, streamName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, goengine_dev.StreamName) bool); ok {
		r0 = rf(ctx, streamName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Load provides a mock function with given fields: ctx, streamName, fromNumber, count, metadataMatcher
func (_m *EventStore) Load(ctx context.Context, streamName goengine_dev.StreamName, fromNumber int64, count *uint, metadataMatcher metadata.Matcher) (goengine_dev.EventStream, error) {
	ret := _m.Called(ctx, streamName, fromNumber, count, metadataMatcher)

	var r0 goengine_dev.EventStream
	if rf, ok := ret.Get(0).(func(context.Context, goengine_dev.StreamName, int64, *uint, metadata.Matcher) goengine_dev.EventStream); ok {
		r0 = rf(ctx, streamName, fromNumber, count, metadataMatcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goengine_dev.EventStream)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, goengine_dev.StreamName, int64, *uint, metadata.Matcher) error); ok {
		r1 = rf(ctx, streamName, fromNumber, count, metadataMatcher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
