// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// MessagePayloadFactory is an autogenerated mock type for the MessagePayloadFactory type
type MessagePayloadFactory struct {
	mock.Mock
}

// CreatePayload provides a mock function with given fields: payloadType, data
func (_m *MessagePayloadFactory) CreatePayload(payloadType string, data interface{}) (interface{}, error) {
	ret := _m.Called(payloadType, data)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, interface{}) interface{}); ok {
		r0 = rf(payloadType, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(payloadType, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
