// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// MessagePayloadResolver is an autogenerated mock type for the MessagePayloadResolver type
type MessagePayloadResolver struct {
	mock.Mock
}

// ResolveName provides a mock function with given fields: payload
func (_m *MessagePayloadResolver) ResolveName(payload interface{}) (string, error) {
	ret := _m.Called(payload)

	var r0 string
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
