// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	goengine_dev "github.com/hellofresh/goengine-dev"
)
import "github.com/stretchr/testify/mock"

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

// Handlers provides a mock function with given fields:
func (_m *Query) Handlers() map[string]goengine_dev.QueryMessageHandler {
	ret := _m.Called()

	var r0 map[string]goengine_dev.QueryMessageHandler
	if rf, ok := ret.Get(0).(func() map[string]goengine_dev.QueryMessageHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]goengine_dev.QueryMessageHandler)
		}
	}

	return r0
}

// Init provides a mock function with given fields:
func (_m *Query) Init() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
