// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import "github.com/hellofresh/goengine"
import mock "github.com/stretchr/testify/mock"

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

// Handlers provides a mock function with given fields:
func (_m *Query) Handlers() map[string]goengine.MessageHandler {
	ret := _m.Called()

	var r0 map[string]goengine.MessageHandler
	if rf, ok := ret.Get(0).(func() map[string]goengine.MessageHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]goengine.MessageHandler)
		}
	}

	return r0
}

// Init provides a mock function with given fields: ctx
func (_m *Query) Init(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
