// Code generated by protoc-gen-go. DO NOT EDIT.
// source: name_changed.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NameChanged struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameChanged) Reset()         { *m = NameChanged{} }
func (m *NameChanged) String() string { return proto.CompactTextString(m) }
func (*NameChanged) ProtoMessage()    {}
func (*NameChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc6381b28373868d, []int{0}
}

func (m *NameChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameChanged.Unmarshal(m, b)
}
func (m *NameChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameChanged.Marshal(b, m, deterministic)
}
func (m *NameChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameChanged.Merge(m, src)
}
func (m *NameChanged) XXX_Size() int {
	return xxx_messageInfo_NameChanged.Size(m)
}
func (m *NameChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_NameChanged.DiscardUnknown(m)
}

var xxx_messageInfo_NameChanged proto.InternalMessageInfo

func (m *NameChanged) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*NameChanged)(nil), "internal.name_changed")
}

func init() { proto.RegisterFile("name_changed.proto", fileDescriptor_cc6381b28373868d) }

var fileDescriptor_cc6381b28373868d = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4b, 0xcc, 0x4d,
	0x8d, 0x4f, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x51, 0x52, 0xe2, 0xe2, 0x41, 0x96, 0x17, 0x12,
	0xe2, 0x62, 0x01, 0xf1, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0xec, 0x24, 0x36, 0xb0,
	0x26, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x49, 0x4e, 0x39, 0x4a, 0x00, 0x00, 0x00,
}
