// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account_deposited.proto

package internal

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountDeposited struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeposited) Reset()         { *m = AccountDeposited{} }
func (m *AccountDeposited) String() string { return proto.CompactTextString(m) }
func (m *AccountDeposited) ProtoMessage()  {}
func (m *AccountDeposited) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee02e7fbf67920c, []int{0}
}

func (m *AccountDeposited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeposited.Unmarshal(m, b)
}
func (m *AccountDeposited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeposited.Marshal(b, m, deterministic)
}
func (m *AccountDeposited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeposited.Merge(m, src)
}
func (m *AccountDeposited) XXX_Size() int {
	return xxx_messageInfo_AccountDeposited.Size(m)
}
func (m *AccountDeposited) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeposited.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeposited proto.InternalMessageInfo

func (m *AccountDeposited) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountDeposited)(nil), "internal.AccountDeposited")
}

func init() { proto.RegisterFile("account_deposited.proto", fileDescriptor_2ee02e7fbf67920c) }

var fileDescriptor_2ee02e7fbf67920c = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x89, 0x4f, 0x49, 0x2d, 0xc8, 0x2f, 0xce, 0x2c, 0x49, 0x4d, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x51, 0xd2, 0xe2,
	0x12, 0x70, 0x84, 0x28, 0x72, 0x81, 0xa9, 0x11, 0x12, 0xe3, 0x62, 0x4b, 0xcc, 0x05, 0x09, 0x49,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x49, 0x6c, 0x60, 0xcd, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x25, 0xeb, 0xd8, 0xcf, 0x57, 0x00, 0x00, 0x00,
}
