// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account_credited.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountCredited struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCredited) Reset()         { *m = AccountCredited{} }
func (m *AccountCredited) String() string { return proto.CompactTextString(m) }
func (*AccountCredited) ProtoMessage()    {}
func (*AccountCredited) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6c24d74b91426e, []int{0}
}

func (m *AccountCredited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCredited.Unmarshal(m, b)
}
func (m *AccountCredited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCredited.Marshal(b, m, deterministic)
}
func (m *AccountCredited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCredited.Merge(m, src)
}
func (m *AccountCredited) XXX_Size() int {
	return xxx_messageInfo_AccountCredited.Size(m)
}
func (m *AccountCredited) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCredited.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCredited proto.InternalMessageInfo

func (m *AccountCredited) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountCredited)(nil), "internal.AccountCredited")
}

func init() { proto.RegisterFile("account_credited.proto", fileDescriptor_5c6c24d74b91426e) }

var fileDescriptor_5c6c24d74b91426e = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x89, 0x4f, 0x2e, 0x4a, 0x4d, 0xc9, 0x2c, 0x49, 0x4d, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x51, 0xd2, 0xe4, 0xe2,
	0x77, 0x84, 0xa8, 0x71, 0x86, 0x2a, 0x11, 0x12, 0xe3, 0x62, 0x4b, 0xcc, 0x05, 0x89, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x49, 0x6c, 0x60, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0xc4, 0x28, 0xc0, 0x55, 0x00, 0x00, 0x00,
}
